<h1>Formulario de Contacto</h1>
<?php
$form = $this->form;
$form->prepare();
/*
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('application/formulario/recibe'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');
*/
$form->setAttributes(array(
    'action' => $this->url.'/contacto',
    'method' => 'post',
    'class'=>'form'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>
<fieldset class="externo">
    <legend>Contacto</legend>
    <fieldset class="interno">
<!--Una Forma de Imprimir Un elemento -->
<p class="for-text">
    <label>Nombre</label>
<?php
    $name = $form->get('nombre');
    //echo $formLabel->openTag().$name->getOption('label')." ";
    echo $this->formInput($name);
    //echo $this->formElementErrors($name);
    //echo $formLabel->closeTag();
?>
</p>
<!--Cargando los Elementos en la vista via factory-->
<p class="for-text">
<?php
    $apellido = $form->get('apellido');
    echo $formLabel->openTag().$apellido->getOption('label')." ";
    echo $formLabel->closeTag();
    echo $this->formInput($apellido);
    //echo $this->formElementErrors($name);
    
?>
</p>
<p class="for-text">
<?php
    $email = $form->get('email');
    echo $formLabel->openTag().$email->getOption('label')." ";
    echo $formLabel->closeTag();
    echo $this->formInput($email);
    //echo $this->formElementErrors($name);
?>
</p>
<p class="for-text">
<?php
    $telefono = $form->get('telefono');
    echo $formLabel->openTag().$telefono->getOption('label')." ";
    echo $formLabel->closeTag();
    echo $this->formInput($telefono);
    //echo $this->formElementErrors($name);
?>
</p>
<!--Otra Forma de Imprimir un elementos-->
<?php echo $this->formElement($form->get('send')) ?>

<?php echo $this->form()->closeTag() ?>
    </fieldset>
</fieldset>




