<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Producto\Module'                        => __DIR__ . '/Module.php',
    'Producto\Controller\SkeletonController' => __DIR__ . '/src/ZendSkeletonModule/Controller/SkeletonController.php',
    'Producto\Framework\TestCase'        => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'Producto\SampleTest'                => __DIR__ . '/tests/ZendSkeletonModule/SampleTest.php',
);