<?php echo $this->doctype();?>
<html lang="es">
    <head>
        <!--Styles-->
        <?php 
         $this->headLink(array('rel' => 'shortcut icon'),'PREPEND')->appendStylesheet($this->basePath().'/css/estilo.css');
         echo $this->headLink();?>
        <!--Scripts-->
        <?php $this->headScript()->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js');
         echo $this->headScript();?>
        
    </head>
    <body>
        <div id="content">
            <header></header>
            <?php echo $this->content; ?>
            <footer></footer>
        </div>
    </body>
</html>