<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
         <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <?php echo $this->headTitle('Sofve.com | Diseño Web, Tecnologia, Resposive Design');?>
        <?php  $this->headMeta()->appendName('author', "Angel Gonzalez");
               $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
               $this->headMeta()->appendName('keywords', "php,formularios,diseño, Desarrollo, soporte, Responsive Design, Diseño Web,");
               $this->headMeta()->appendName('description', "Diseño y Desarrollo de Sistemas Webs");
               $this->headMeta()->setProperty('og:title', "Sofve.com Tus Ideas Son Nuestra Ispiración");
               $this->headMeta()->setProperty('og:type', "sitio web");
               $this->headMeta()->setProperty('og:url', "http://www.sofve.com");
               $this->headMeta()->setProperty('og:site_name', "SofVe");
        echo $this->headMeta();
        ?>
        <!--styles-->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'img/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/icono.ico'))
                        ->prependStylesheet($this->basePath().'/css/estilo.css')
                        ->prependStylesheet($this->basePath().'/css/cycle.min.css')
                        ->prependStylesheet($this->basePath().'/css/form.css');  ?>
        <!--scripts-->

        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.cycle.all.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js', 'text/javascript')?>
        <script src="js/jquery.cycle.all.js" type="text/javascript"></script>
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(["_setAccount", "UA-27946966-1"]);
            _gaq.push(["_trackPageview"]);
            var pluginUrl =
            '//www.google-analytics.com/plugins/ga/inpage_linkid.js';
           _gaq.push(['_require', 'inpage_linkid', pluginUrl]);
            (function() {
              var ga = document.createElement("script"); ga.type = "text/javascript"; ga.async = true;
              ga.src = ("https:" == document.location.protocol ? "https://ssl" : "http://www") + ".google-analytics.com/ga.js";
              var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ga, s);
            })();
          </script>
    </head>
    <body>
    <header>
        <div class="panel-lef">
            <div class="logo">
                <img alt="sofve.com" src="<?php echo $this->basePath()."/img/sofve.png"?>" style="width: 80px; height: 60px;" />
            </div>
        </div>
        <div class="panel-righ">
            <ul class="menu">
                <li>
                    <a href="<?php echo $this->url('home');  ?>">Bienvenidos</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('noticia');  ?>">Noticias</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('contacto');  ?>">Contactanos</a>
                </li>
            </ul>
        </div>
    </header>
    <section>
        <?php echo $this->content; ?>
    </section>
    <footer>
        <p>Todos los derechos reservados SofVe.com Desarrollo web de Venezuela - 2013</p>
    </footer>
    <?php $this->inlineScript(); ?>
    <script>
    $(document).ready(function(){
        $('#slideshow').after('<div id="nav" class="nav">').cycle({
            fx:     'fade',
            speed:  'slow',
            timeout: 5000,
            pager:  '#nav'
        });
        $('#slideshow').hover(
        function(){
            $(this).cycle('pause');
        },
        function(){
            $(this).cycle('resume');
        });
        $('#nav').find('a').click(function(){
        $('#slideshow').cycle('pause');
        return false;
        });

    })
    </script>
    </body>

</html>
