<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        	->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        	->prependStylesheet($this->basePath() . '/css/style.css')
        	->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        	->prependStylesheet($this->basePath() . '/sliders/revolution_slider/css/settings.css')
        	->prependStylesheet($this->basePath() . '/sliders/revolution_slider/css/creative_slider.css')
        	?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        	->prependFile($this->basePath() . '/sliders/revolution_slider/js/jquery.themepunch.plugins.min.js')
        	->prependFile($this->basePath() . '/sliders/revolution_slider/js/jquery.themepunch.revolution.min.js')
        	->prependFile($this->basePath() . '/sliders/revolution_slider/js/parallax.js')
			->prependFile($this->basePath() . '/js/bootstrap.min.js')
        	->prependFile($this->basePath() . '/js/jquery-1.8.2.min.js')
        	?>

    </head>
    <body>
	<header>
		<div class="logo-primary">
		<a class="">Sofve</a>
		</div>
		<div class="header-action"></div>

	</header>
        <section>
			 <?php echo $this->content; ?>
		</section>

        <footer>
        	<p>&copy; 2013 por SofVe.com Todos los Derechos Reservados <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
         <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <script>
		//	var $=jQuery;
		//	$.noConflict();

			$(document).ready(function() {

			if ($.fn.cssOriginal!=undefined)
			$.fn.css = $.fn.cssOriginal;

			$('.fullwidthbanner').revolution(
			{
			delay:9000,
			startwidth:800,
			startheight:350,

			onHoverStop:"on",						// Stop Banner Timet at Hover on Slide on/off

			thumbWidth:100,							// Thumb With and Height and Amount (only if navigation Tyope set to thumb !)
			thumbHeight:300,
			thumbAmount:3,

			hideThumbs:200,
			navigationType:"none",					//bullet, thumb, none, both	 (No Shadow in Fullwidth Version !)
			navigationArrows:"verticalcentered",		//nexttobullets, verticalcentered, none

			touchenabled:"on",						// Enable Swipe Function : on/off

			navOffsetHorizontal:0,
			navOffsetVertical:20,

			stopAtSlide:-1,							// Stop Timer if Slide "x" has been Reached. If stopAfterLoops set to 0, then it stops already in the first Loop at slide X which defined. -1 means do not stop at any slide. stopAfterLoops has no sinn in this case.
			stopAfterLoops:-1,						// Stop Timer if All slides has been played "x" times. IT will stop at THe slide which is defined via stopAtSlide:x, if set to -1 slide never stop automatic



			fullWidth:"on",

			shadow:0								//0 = no Shadow, 1,2,3 = 3 Different Art of Shadows -  (No Shadow in Fullwidth Version !)

			});
			})
		</script>
    </body>
</html>