<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
         <?php echo $this->headTitle('Sofve.com | Diseño Web, Tecnologia, Resposive Design');?>
         <?php $this->headMeta()->appendName('author', "Angel Gonzalez");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
$this->headMeta()->appendName('keywords', "php,formularios,diseño, Desarrollo, soporte, Responsive Design, Diseño Web,");
$this->headMeta()->appendName('description', "Diseño y Desarrollo de Sistemas Webs");
$this->headMeta()->setProperty('og:title', "Sofve.com Tus Ideas Son Nuestra Ispiración");
$this->headMeta()->setProperty('og:type', "sitio web");
$this->headMeta()->setProperty('og:url', "http://www.sofve.com");
$this->headMeta()->setProperty('og:site_name', "SofVe");
echo $this->headMeta();

?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))->prependStylesheet($this->basePath() . '/css/bootstrap.css')->prependStylesheet($this->basePath() . '/css/style.css')->prependStylesheet($this->basePath() . '/css/cycle.min.css')

?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))->prependFile($this->basePath() . '/js/jquery.cycle.all.js')->prependFile($this->basePath() . '/js/bootstrap.min.js')->prependFile($this->basePath() . '/js/jquery.min.js', 'text/javascript')
?>
			<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(["_setAccount", "UA-27946966-1"]);
			_gaq.push(["_trackPageview"]);
			var pluginUrl =
			'//www.google-analytics.com/plugins/ga/inpage_linkid.js';
			_gaq.push(['_require', 'inpage_linkid', pluginUrl]);
			(function() {
			var ga = document.createElement("script"); ga.type = "text/javascript"; ga.async = true;
			ga.src = ("https:" == document.location.protocol ? "https://ssl" : "http://www") + ".google-analytics.com/ga.js";
			var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ga, s);
			})();
			</script>

    </head>
    <body class="background">
	<!--header>
		<div class="logo-primary">
		<a class="">Sofve</a>
		</div>
		<div class="header-action"></div>

	</header-->
	<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
	  <div class="container">
	    <div class="navbar-header">
	      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a href="/" class="navbar-brand">Sofve</a>
	    </div>
	    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
	      <ul class="nav navbar-nav">
	            <li>
                    <a href="<?php echo $this->url('home'); ?>">Bienvenidos</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('noticia'); ?>">Noticias</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('contacto'); ?>">Contactanos</a>
                </li>
	      </ul>
	      <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
	    </nav>
	  </div>
	</header>
        <section>
			 <?php echo $this->content; ?>
		</section>

        <footer>
        	<p>&copy; 2013 por SofVe.com Todos los Derechos Reservados <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
         <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <script>
    $(document).ready(function(){
    	$('#slideshow').after('<div id="nav" class="nav">').cycle({
    		fx:     'fade',
    		speed:  'slow',
    		timeout: 1500,
    		pager:  '#nav'
    	});
    	$('#slideshow').hover(
    	function(){
    		$(this).cycle('pause');
    	},
    	function(){
    		$(this).cycle('resume');
    	});
    	$('#nav').find('a').click(function(){
    		$('#slideshow').cycle('pause');
    		return false;
    	});

    })
    </script>
    </body>
</html>