<article class="sliders">
    <h1>TUS IDEAS SON NUESTRA INSPIRACION</h1>
    <div class="gdhp-wrapper">
        <ul id="slideshow" class="slides" style="position: relative;">
            <li  class="gdhp-slide-outright"> 
                <div class="slideshow-decription right">
                <h3>Diseñamos tu Sitio Web Profesional</h3>
                <p>!Rápido y Fácil!<sup class="supSymbol"></sup> Contactamos y obten asesoria al Instante con nuestros Especialistas</p>
                <a class="flat-btn-grn">Contactar</a> <span>Con precios a partir de 3.000 Bs..</span>
                </div>   
            </li>
            <li class="gdhp-slide-wsb">
                <div class="slideshow-decription left">
                <h3>Suscribete a Sofve.com</h3>
                <p>Proximanete estaras Participando en el diseño de tu sitio web totalmente Gratis</p>
                <a class="flat-btn-grn">Ver Noticia</a> <span>Para Mayor Informacion</span>
                </div>   
            </li>
        </ul>
    </div>
    <br>
</article>
</article>
<article class="conten">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttributes(array(
        'action'=>$this->url.'application/index/registra',
        'method'=>'post',
        'class'=>'forma'
    ));
    $formLabel = $this->plugin('formLabel');
    echo $this->form()->openTag($form);
    
    ?>
    <h3>Recibe Nuestras Promociones y Servicios</h3>
    <fieldset class="externo">
        <fieldset class="interno">
    <p class="for-text">
        <?php
                $email = $form->get('email');
                echo $formLabel->openTag().$email->getOption('label')." ";
                echo $formLabel->closeTag();
                echo $this->formInput($email);
        ?>
        </p>
        <?php 
               echo $this->formElement($form->get('send'))
        ?>
        </fieldset>
    </fieldset>
    <h1>
    <div>
        Noticias de La Semana
        <div class="extensor">
        </div>
    </div>
    </h1>
</article>
