<article>
    <h2>TUS IDEAS SON NUESTRA INSPIRACION</h2>
    <div class="gdhp-wrapper">
        <ul id="slideshow" class="slides" style="position: relative;">
            <li  class="gdhp-slide-outright">
                <div class="slideshow-decription right">
                <h3>Simplifica las finanzas de tus negocios</h3>
                <p>No más hojas de cálculo. Outright<sup class="supSymbol">®</sup> ingresa y organiza tus finanzas comerciales automáticamente.</p>
                <a class="flat-btn-grn">Inicio</a> <span>Con un costo a partir de Bs.6,40 /mo</span>
                </div>   
            </li>
            <li class="gdhp-slide-wsb">
                <div class="slideshow-decription left">
                <h3>Genera fácilmente un sitio web profesional</h3>
                <p>¡Rápido y fácil! No se requieren conocimientos técnicos o de codificación.</p>
                <a class="flat-btn-grn">Inicio</a> <span>Con un costo a partir de Bs.12,99 /mo</span>
                </div>   
            </li>
        </ul>
    </div>
</article>