<article class="registro">
    <h3>Registrate en Sofve</h3>
    <div class="panel-lef">
        <form action="{accion}" method="{metodo}" enctype="{tipo}" class="form" id="{id}">
                <fieldset class="externo">
                <fieldset class="interno">
                        <legend>{legend}</legend>
                        <p id="p_{id}" class="for-text">
                        <label for="{id}">{label}{obligatorio}: </label>
                        <input type="{tipo}" class="{clase}" id="{id}" name="{name}" value="{value}" {deshabilitado} {solo_lectura}>{adicionales}
                        <span class="for-info">{info}</span>
                        </p>
                </fieldset>
              <div id="{id}_insertar">
              </div>
              <div class="campos_ocultos">
                {campos_ocultos}
              </div>
              <p class="for-submit">
                 {botones}
              </p>
                </fieldset>
        </form>
    </div>
</article>    