<article>
    <div class="line"></div>
    <!--h3>Proximante estara Disponible la sesion de Noticias</h3-->
	<div class="noticia">
        <div class="header">
            <div class="title">
                <h2><?php echo $this->valor['titulo_post']; ?></h2>
            </div>
            <div class="title-content"><?php echo $this->valor['contenido_post'] ?></div>
        </div>
        <div  class="section">
            <div class="article"><?php echo $this->valor['texto_post'] ?></div>
        </div>
        <div class="footer"></div>
    </div>
    <div style="clear: both"></div>
</article>
