<article class="container">
	<h3 class="">
	<div class="orange">
	 Noticias
	<div class="extensor orange">
	</div>
	</div>
	</h3>
    <!--h3>Proximante estara Disponible la sesion de Noticias</h3-->
	<div class="noticia">
        <div class="header">
            <div class="title">
                <h2><?php echo $this->valor['titulo_post']; ?></h2>
            </div>
            <div class="title-content"><?php echo $this->valor['contenido_post'] ?></div>
        </div>
        <div  class="section">
            <div class="article"><?php echo $this->valor['texto_post'] ?></div>
        </div>
        <div class="footer"></div>
        <?php
if (isset($this->valor['video_post'])) { ?>
		<iframe width="420" height="315" src="<?php echo $this->valor['video_post'] ?>" frameborder="0" allowfullscreen></iframe>
		<?php
}

?>

    </div>
    <div style="clear: both"></div>
</article>
